import { Note, NoteFolder, NoteTag, NoteTemplateConfig } from "@/types/notes";

// Mock folders
export const mockFolders: NoteFolder[] = [
    {
        id: "folder-1",
        name: "Trading Ideas",
        icon: "💡",
        parentId: null,
        isExpanded: true,
        createdAt: new Date("2024-12-01"),
        updatedAt: new Date("2024-12-20"),
    },
    {
        id: "folder-2",
        name: "Market Analysis",
        icon: "📊",
        parentId: null,
        isExpanded: true,
        createdAt: new Date("2024-12-05"),
        updatedAt: new Date("2024-12-19"),
    },
    {
        id: "folder-3",
        name: "Psychology",
        icon: "🧠",
        parentId: null,
        isExpanded: false,
        createdAt: new Date("2024-12-10"),
        updatedAt: new Date("2024-12-18"),
    },
    {
        id: "folder-4",
        name: "Playbook Notes",
        icon: "📖",
        parentId: null,
        isExpanded: false,
        createdAt: new Date("2024-12-12"),
        updatedAt: new Date("2024-12-17"),
    },
];

// Mock tags
export const mockTags: NoteTag[] = [
    { id: "tag-1", name: "Important", color: "bg-red-500" },
    { id: "tag-2", name: "Review", color: "bg-yellow-500" },
    { id: "tag-3", name: "Forex", color: "bg-blue-500" },
    { id: "tag-4", name: "Crypto", color: "bg-purple-500" },
    { id: "tag-5", name: "Strategy", color: "bg-emerald-500" },
    { id: "tag-6", name: "Risk Management", color: "bg-orange-500" },
];

// Default content for a new note
const defaultContent = JSON.stringify([
    {
        id: "1",
        type: "paragraph",
        props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
        content: [{ type: "text", text: "Start writing here...", styles: {} }],
        children: [],
    },
]);

// Mock notes
export const mockNotes: Note[] = [
    {
        id: "note-1",
        title: "FOMC Trade Plan",
        content: JSON.stringify([
            {
                id: "h1",
                type: "heading",
                props: { level: 1, textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "FOMC Trade Strategy", styles: {} }],
                children: [],
            },
            {
                id: "p1",
                type: "paragraph",
                props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "Key approach for FOMC announcements:", styles: {} }],
                children: [],
            },
            {
                id: "ul1",
                type: "bulletListItem",
                props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "Wait for initial spike to settle (15-30 mins)", styles: {} }],
                children: [],
            },
            {
                id: "ul2",
                type: "bulletListItem",
                props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "Look for divergence on USD pairs", styles: {} }],
                children: [],
            },
            {
                id: "ul3",
                type: "bulletListItem",
                props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "Target 2R minimum on breakout trades", styles: {} }],
                children: [],
            },
            {
                id: "cb1",
                type: "checkListItem",
                props: { checked: true, textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "Review previous FOMC reactions", styles: {} }],
                children: [],
            },
            {
                id: "cb2",
                type: "checkListItem",
                props: { checked: false, textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "Set alerts on key levels", styles: {} }],
                children: [],
            },
        ]),
        folderId: "folder-1",
        tags: ["tag-1", "tag-3"],
        icon: "📈",
        coverImage: null,
        isFavorite: true,
        isArchived: false,
        createdAt: new Date("2024-12-15"),
        updatedAt: new Date("2024-12-20"),
    },
    {
        id: "note-2",
        title: "Weekly Market Outlook",
        content: JSON.stringify([
            {
                id: "h1",
                type: "heading",
                props: { level: 1, textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "Week 51 - Market Outlook", styles: {} }],
                children: [],
            },
            {
                id: "h2",
                type: "heading",
                props: { level: 2, textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "Key Events", styles: {} }],
                children: [],
            },
            {
                id: "p1",
                type: "numberedListItem",
                props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "FOMC Rate Decision - Wednesday", styles: { bold: true } }],
                children: [],
            },
            {
                id: "p2",
                type: "numberedListItem",
                props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "BOE Rate Decision - Thursday", styles: {} }],
                children: [],
            },
            {
                id: "p3",
                type: "numberedListItem",
                props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "Core PCE - Friday", styles: {} }],
                children: [],
            },
        ]),
        folderId: "folder-2",
        tags: ["tag-2"],
        icon: "📅",
        coverImage: null,
        isFavorite: false,
        isArchived: false,
        createdAt: new Date("2024-12-16"),
        updatedAt: new Date("2024-12-16"),
    },
    {
        id: "note-3",
        title: "Overtrading Reflection",
        content: JSON.stringify([
            {
                id: "h1",
                type: "heading",
                props: { level: 1, textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "Why Did I Overtrade Today?", styles: {} }],
                children: [],
            },
            {
                id: "p1",
                type: "paragraph",
                props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "After losing my first trade, I felt the need to \"make it back.\" This is revenge trading.", styles: {} }],
                children: [],
            },
            {
                id: "h2",
                type: "heading",
                props: { level: 2, textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "Action Items", styles: {} }],
                children: [],
            },
            {
                id: "cb1",
                type: "checkListItem",
                props: { checked: true, textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "Take a 30-minute break after any loss", styles: {} }],
                children: [],
            },
            {
                id: "cb2",
                type: "checkListItem",
                props: { checked: false, textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "Limit to 3 trades per day maximum", styles: {} }],
                children: [],
            },
        ]),
        folderId: "folder-3",
        tags: ["tag-1", "tag-6"],
        icon: "🧘",
        coverImage: null,
        isFavorite: true,
        isArchived: false,
        createdAt: new Date("2024-12-18"),
        updatedAt: new Date("2024-12-18"),
    },
    {
        id: "note-4",
        title: "Breakout Strategy v2",
        content: JSON.stringify([
            {
                id: "h1",
                type: "heading",
                props: { level: 1, textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [{ type: "text", text: "Breakout Strategy - Updated Rules", styles: {} }],
                children: [],
            },
            {
                id: "p1",
                type: "paragraph",
                props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
                content: [
                    { type: "text", text: "Entry Criteria:", styles: { bold: true } },
                    { type: "text", text: " Wait for clean break of range with volume confirmation", styles: {} },
                ],
                children: [],
            },
        ]),
        folderId: "folder-4",
        tags: ["tag-5"],
        icon: "🚀",
        coverImage: null,
        isFavorite: false,
        isArchived: false,
        createdAt: new Date("2024-12-17"),
        updatedAt: new Date("2024-12-19"),
    },
    {
        id: "note-5",
        title: "Quick Notes",
        content: defaultContent,
        folderId: null,
        tags: [],
        icon: "📝",
        coverImage: null,
        isFavorite: false,
        isArchived: false,
        createdAt: new Date("2024-12-20"),
        updatedAt: new Date("2024-12-20"),
    },
];

// Note templates
export const noteTemplates: NoteTemplateConfig[] = [
    {
        id: "blank",
        name: "Blank",
        description: "Start with a blank page",
        icon: "📄",
        defaultContent: defaultContent,
    },
    {
        id: "trade-analysis",
        name: "Trade Analysis",
        description: "Analyze a specific trade",
        icon: "📊",
        defaultContent: JSON.stringify([
            { id: "1", type: "heading", props: { level: 1 }, content: [{ type: "text", text: "Trade Analysis", styles: {} }], children: [] },
            { id: "2", type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Setup", styles: {} }], children: [] },
            { id: "3", type: "paragraph", content: [{ type: "text", text: "Describe the trade setup here...", styles: {} }], children: [] },
            { id: "4", type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Entry & Exit", styles: {} }], children: [] },
            { id: "5", type: "paragraph", content: [{ type: "text", text: "Entry reason and exit strategy...", styles: {} }], children: [] },
            { id: "6", type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Lessons Learned", styles: {} }], children: [] },
            { id: "7", type: "paragraph", content: [{ type: "text", text: "What did you learn?", styles: {} }], children: [] },
        ]),
    },
    {
        id: "weekly-plan",
        name: "Weekly Plan",
        description: "Plan your trading week",
        icon: "📅",
        defaultContent: JSON.stringify([
            { id: "1", type: "heading", props: { level: 1 }, content: [{ type: "text", text: "Weekly Trading Plan", styles: {} }], children: [] },
            { id: "2", type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Key Events", styles: {} }], children: [] },
            { id: "3", type: "checkListItem", props: { checked: false }, content: [{ type: "text", text: "Review economic calendar", styles: {} }], children: [] },
            { id: "4", type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Focus Pairs", styles: {} }], children: [] },
            { id: "5", type: "bulletListItem", content: [{ type: "text", text: "EUR/USD", styles: {} }], children: [] },
            { id: "6", type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Goals", styles: {} }], children: [] },
            { id: "7", type: "checkListItem", props: { checked: false }, content: [{ type: "text", text: "Stick to max 3 trades per day", styles: {} }], children: [] },
        ]),
    },
    {
        id: "psychology-reflection",
        name: "Psychology Reflection",
        description: "Reflect on your trading mindset",
        icon: "🧠",
        defaultContent: JSON.stringify([
            { id: "1", type: "heading", props: { level: 1 }, content: [{ type: "text", text: "Trading Psychology Reflection", styles: {} }], children: [] },
            { id: "2", type: "heading", props: { level: 2 }, content: [{ type: "text", text: "How am I feeling?", styles: {} }], children: [] },
            { id: "3", type: "paragraph", content: [{ type: "text", text: "Describe your current mental state...", styles: {} }], children: [] },
            { id: "4", type: "heading", props: { level: 2 }, content: [{ type: "text", text: "What triggered this?", styles: {} }], children: [] },
            { id: "5", type: "paragraph", content: [{ type: "text", text: "Identify triggers...", styles: {} }], children: [] },
            { id: "6", type: "heading", props: { level: 2 }, content: [{ type: "text", text: "Action Steps", styles: {} }], children: [] },
            { id: "7", type: "checkListItem", props: { checked: false }, content: [{ type: "text", text: "Step 1", styles: {} }], children: [] },
        ]),
    },
];
